framework:
    messenger:
        default_bus: command.bus

        # Defining which transport will handle failed messages
        failure_transport: failed
        transports:
            # https://symfony.com/doc/current/messenger.html#transports
            async:
                serializer: messenger.transport.symfony_serializer
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: priority_normal
                    queues:
                        messages_normal:
                            binding_keys: [ priority_normal ]
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # queue_name: high # option queue_name does not exist for AMQP, only for Doctrine
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: priority_high
                    queues:
                        messages_high:
                            binding_keys: [ priority_high ]
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://' # special type of transport, mainly for dev environment and debugging; simulates async transport while not needing to run messenger:consume command
        routing:
            # Route your messages to the transports
            'App\Message\Command\AddPonkaToImage': async_priority_high
            'App\Message\Event\ImagePostDeletedEvent': async
        buses:
            command.bus:
                default_middleware: true
                middleware:
                    - App\Middleware\AuditMiddleware
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Middleware\AuditMiddleware
            query.bus: ~