framework:
    messenger:
        default_bus: command.bus

        # Defining which transport will handle failed messages
        failure_transport: failed
        transports:
            # https://symfony.com/doc/current/messenger.html#transports
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    delay: 500
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: high
                retry_strategy:
                    delay: 500
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://' # special type of transport, mainly for dev environment and debugging; simulates async transport while not needing to run messenger:consume command
        routing:
            # Route your messages to the transports
            'App\Message\Command\AddPonkaToImage': async_priority_high
            'App\Message\Event\ImagePostDeletedEvent': async

        buses:
            command.bus:
                default_middleware: true
                middleware:
                    - App\Middleware\AuditMiddleware
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Middleware\AuditMiddleware
            query.bus: ~